### 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "username": "juwon",
  "password": "1234"
}

### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "juwon",
  "password": "1234"
}

### 내 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJqdXdvbiIsImlhdCI6MTc4MzE2MTg2NCwiZXhwIjoxNzgzMTY1NDY0fQ.F8HrafNc6WXa6aniUfxDKIIolHI9alG0bkrkCQg0cYQ

### 프로젝트 생성
POST http://localhost:8080/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJqdXdvbiIsImlhdCI6MTc4MzE3MTIxMiwiZXhwIjoxNzgzMTc0ODEyfQ.zHKUryRYcWvcwLq-109fTPheXXrRKF6x4Z_39I6P6As
Content-Type: application/json

{
  "title": "DevTask 만들기",
  "description": "두 번째 풀스택 프로젝트"
}

### 내 프로젝트 목록 조회
GET http://localhost:8080/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJqdXdvbiIsImlhdCI6MTc4MzE3MTIxMiwiZXhwIjoxNzgzMTc0ODEyfQ.zHKUryRYcWvcwLq-109fTPheXXrRKF6x4Z_39I6P6As